version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: goledger
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initializeDataBaseTable.sql:/docker-entrypoint-initdb.d/initializeDataBaseTable.sql

volumes:
  postgres_data:
